# Site settings
title: Code Beers
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Code Beers is a periodic meeting for developers who wants to talk,
  share knowledge and drink beer.
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://paulodiovani.github.io/" # the base hostname & protocol for your site
# twitter_username: codebeers
# github_username:  codebeers

# permalinks for blog posts
permalink: "/blog/:categories/:year/:month/:day/:title/"
paginate_path: "blog/page:num/"
paginate: 5

# store pages in _pages/ folder
include: ['_pages']
relative_permalinks: false

# Build settings
markdown: kramdown

