# Site settings
title: Code Beers
description: > # this means to ignore newlines until "baseurl:"
  Code Beers is a periodic meeting for developers who wants to talk,
  share knowledge and drink beer.
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codebeers.github.io/" # the base hostname & protocol for your site
github_url: "https://github.com/codebeers/codebeers.github.io"

contacts:
  -
    name: Gabriel Molter
    email: gabriel.molter@gmail.com
    twitter_username: gabriel_molter
    # github_username: gabriel_molter
  -
    name: Paulo Diovani Gonçalves
    email: paulo@diovani.com
    twitter_username: paulodiovani
    github_username:  paulodiovani

# permalinks for blog posts
permalink: "/blog/:categories/:year/:month/:day/:title/"
paginate_path: "blog/page:num/"
paginate: 5

# store pages in _pages/ folder
include: ['_pages']
relative_permalinks: false

# Build settings
markdown: kramdown

